In [1]:
import numpy as np

# Создание матрицы
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print("Исходная матрица:")
print(m)

# Доступ к элементам
print("\nЭлемент m[1,0]:", m[1,0])
print("Вторая строка:", m[1, :])
print("Третий столбец:", m[:, 2])
print("Часть строки (со 2-го элемента):", m[1, 2:])

Исходная матрица:
[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]

Элемент m[1,0]: 5
Вторая строка: [[5 6 7 8]]
Третий столбец: [[3]
 [7]
 [5]]
Часть строки (со 2-го элемента): [[7 8]]


In [2]:
import numpy as np

# Создание матрицы
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 1, 5, 7]])

print("Матрица:")
print(m)
print(f"Размерность (shape): {m.shape}")
print(f"\nМаксимальный элемент (все): {m.max()}")
print(f"Максимум по строкам (axis=1): {m.max(axis=1)}")
print(f"Максимум по столбцам (axis=0): {m.max(axis=0)}")
print(f"\nСреднее значение: {m.mean():.2f}")
print(f"Среднее по строкам: {m.mean(axis=1)}")
print(f"Среднее по столбцам: {m.mean(axis=0)}")
print(f"\nСумма всех элементов: {m.sum()}")
print(f"Стандартное отклонение: {m.std():.2f}")

Матрица:
[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]
Размерность (shape): (3, 4)

Максимальный элемент (все): 9
Максимум по строкам (axis=1): [4 8 9]
Максимум по столбцам (axis=0): [9 6 7 8]

Среднее значение: 4.83
Среднее по строкам: [2.5 6.5 5.5]
Среднее по столбцам: [5.         3.         5.         6.33333333]

Сумма всех элементов: 58
Стандартное отклонение: 2.58


In [3]:
import numpy as np

# Создание массива
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Исходный массив:", nums)

# Создание булевой маски
less_then_5 = nums < 5
print("Маска (nums < 5):", less_then_5)

# Фильтрация с помощью маски
filtered = nums[less_then_5]
print("Элементы < 5:", filtered)

# Замена элементов по условию
nums[nums < 5] = 10
print("Массив после замены (<5 → 10):", nums)

# Работа с двумерным массивом
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 1, 5, 7]])

# Сложное условие (элементы от 3 до 7)
mask = np.logical_and(m >= 3, m <= 7)
print("\nИсходная матрица:")
print(m)
print("Маска (3 ≤ элемент ≤ 7):")
print(mask)
print("Элементы, удовлетворяющие условию:")
print(m[mask])

Исходный массив: [ 1  2  3  4  5  6  7  8  9 10]
Маска (nums < 5): [ True  True  True  True False False False False False False]
Элементы < 5: [1 2 3 4]
Массив после замены (<5 → 10): [10 10 10 10  5  6  7  8  9 10]

Исходная матрица:
[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]
Маска (3 ≤ элемент ≤ 7):
[[False False  True  True]
 [ True  True  True False]
 [False False  True  True]]
Элементы, удовлетворяющие условию:
[3 4 5 6 7 5 7]


In [4]:
import numpy as np

# np.arange - создание последовательности
print("1. np.arange(10):", np.arange(10))
print("2. np.arange(5, 15):", np.arange(5, 15))
print("3. np.arange(1, 10, 1.5):", np.arange(1, 10, 1.5))

# np.zeros и np.eye
print("\n4. np.zeros((3,4)) - нулевая матрица:")
print(np.zeros((3, 4)))
print("\n5. np.eye(4) - единичная матрица:")
print(np.eye(4))

# np.diag - диагональная матрица
print("\n6. np.diag([5, 10, 15, 20]) - диагональная матрица:")
print(np.diag([5, 10, 15, 20]))

# np.ravel - преобразование в одномерный массив
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n7. Исходная матрица 3×3:")
print(A)
print("   np.ravel(A) (порядок 'C' - по строкам):", np.ravel(A))
print("   np.ravel(A, order='F') (по столбцам):", np.ravel(A, order='F'))

# np.random.permutation - перемешивание
print("\n8. np.random.permutation(10):", np.random.permutation(10))
arr = np.array([10, 20, 30, 40, 50])
print("   Исходный массив:", arr)
print("   Перемешанный:", np.random.permutation(arr))

1. np.arange(10): [0 1 2 3 4 5 6 7 8 9]
2. np.arange(5, 15): [ 5  6  7  8  9 10 11 12 13 14]
3. np.arange(1, 10, 1.5): [1.  2.5 4.  5.5 7.  8.5]

4. np.zeros((3,4)) - нулевая матрица:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

5. np.eye(4) - единичная матрица:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

6. np.diag([5, 10, 15, 20]) - диагональная матрица:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

7. Исходная матрица 3×3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
   np.ravel(A) (порядок 'C' - по строкам): [1 2 3 4 5 6 7 8 9]
   np.ravel(A, order='F') (по столбцам): [1 4 7 2 5 8 3 6 9]

8. np.random.permutation(10): [5 3 7 0 9 2 1 6 4 8]
   Исходный массив: [10 20 30 40 50]
   Перемешанный: [30 10 20 50 40]


In [5]:
import numpy as np

# Создание матриц
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.array([[1, 2],
              [3, 4]])

print("=== УМНОЖЕНИЕ МАТРИЦЫ НА ЧИСЛО ===")
print("Матрица A:")
print(A)
print("3 × A:")
print(3 * A)

print("\n=== СЛОЖЕНИЕ МАТРИЦ ===")
D = np.array([[5, 6], [7, 8]])
print("C + D:")
print(C + D)

print("\n=== МАТРИЧНОЕ УМНОЖЕНИЕ ===")
print("A (2×3) × B (3×2) =")
result = A @ B
print(result)
print(f"Размерность результата: {result.shape}")

print("\n=== ДЕТАЛЬНЫЙ РАСЧЕТ ===")
print("result[0,0] = 1×7 + 2×9 + 3×11 =", 1*7 + 2*9 + 3*11)
print("result[0,1] = 1×8 + 2×10 + 3×12 =", 1*8 + 2*10 + 3*12)
print("result[1,0] = 4×7 + 5×9 + 6×11 =", 4*7 + 5*9 + 6*11)
print("result[1,1] = 4×8 + 5×10 + 6×12 =", 4*8 + 5*10 + 6*12)

print("\n=== ПРОВЕРКА НЕКОММУТАТИВНОСТИ ===")
print("C × D:")
print(C @ D)
print("D × C:")
print(D @ C)
print("C × D = D × C?", np.array_equal(C @ D, D @ C))

=== УМНОЖЕНИЕ МАТРИЦЫ НА ЧИСЛО ===
Матрица A:
[[1 2 3]
 [4 5 6]]
3 × A:
[[ 3  6  9]
 [12 15 18]]

=== СЛОЖЕНИЕ МАТРИЦ ===
C + D:
[[ 6  8]
 [10 12]]

=== МАТРИЧНОЕ УМНОЖЕНИЕ ===
A (2×3) × B (3×2) =
[[ 58  64]
 [139 154]]
Размерность результата: (2, 2)

=== ДЕТАЛЬНЫЙ РАСЧЕТ ===
result[0,0] = 1×7 + 2×9 + 3×11 = 58
result[0,1] = 1×8 + 2×10 + 3×12 = 64
result[1,0] = 4×7 + 5×9 + 6×11 = 139
result[1,1] = 4×8 + 5×10 + 6×12 = 154

=== ПРОВЕРКА НЕКОММУТАТИВНОСТИ ===
C × D:
[[19 22]
 [43 50]]
D × C:
[[23 34]
 [31 46]]
C × D = D × C? False


In [6]:
import numpy as np

# Создание матрицы
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Исходная матрица A (2×3):")
print(A)

# Разные способы транспонирования
print("\n=== СПОСОБЫ ТРАНСПОНИРОВАНИЯ ===")
print("A.T:")
print(A.T)
print("np.transpose(A):")
print(np.transpose(A))
print("A.transpose():")
print(A.transpose())

# Свойства транспонирования
print("\n=== СВОЙСТВА ТРАНСПОНИРОВАНИЯ ===")
print("Свойство 1: (A^T)^T = A")
print((A.T).T)
print("Равны?", np.array_equal(A, (A.T).T))

B = np.array([[7, 8, 9],
              [10, 11, 12]])

print("\nСвойство 2: (A + B)^T = A^T + B^T")
print("(A + B)^T:")
print((A + B).T)
print("A^T + B^T:")
print(A.T + B.T)

# След матрицы
print("\n=== СЛЕД МАТРИЦЫ (trace) ===")
C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Матрица C:")
print(C)
print(f"След C (np.trace): {np.trace(C)}")
print(f"След C (ручной расчет): {C[0,0] + C[1,1] + C[2,2]}")
print(f"След C^T: {np.trace(C.T)}")
print(f"След C = след C^T? {np.trace(C) == np.trace(C.T)}")

Исходная матрица A (2×3):
[[1 2 3]
 [4 5 6]]

=== СПОСОБЫ ТРАНСПОНИРОВАНИЯ ===
A.T:
[[1 4]
 [2 5]
 [3 6]]
np.transpose(A):
[[1 4]
 [2 5]
 [3 6]]
A.transpose():
[[1 4]
 [2 5]
 [3 6]]

=== СВОЙСТВА ТРАНСПОНИРОВАНИЯ ===
Свойство 1: (A^T)^T = A
[[1 2 3]
 [4 5 6]]
Равны? True

Свойство 2: (A + B)^T = A^T + B^T
(A + B)^T:
[[ 8 14]
 [10 16]
 [12 18]]
A^T + B^T:
[[ 8 14]
 [10 16]
 [12 18]]

=== СЛЕД МАТРИЦЫ (trace) ===
Матрица C:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
След C (np.trace): 15
След C (ручной расчет): 15
След C^T: 15
След C = след C^T? True


In [7]:
import numpy as np

# Создание матрицы 2×2
A = np.array([[1, 2],
              [3, 4]])

print("=== ОПРЕДЕЛИТЕЛЬ МАТРИЦЫ 2×2 ===")
print("Матрица A:")
print(A)
det_A = np.linalg.det(A)
print(f"det(A) = 1×4 - 2×3 = {det_A}")

# Создание матрицы 3×3
B = np.array([[4, -1, 2],
              [10, 4, -1],
              [8, 3, 1]])

print("\n=== ОПРЕДЕЛИТЕЛЬ МАТРИЦЫ 3×3 ===")
print("Матрица B:")
print(B)
det_B = np.linalg.det(B)
print(f"det(B) = {det_B:.0f}")

print("\n=== ОБРАТНАЯ МАТРИЦА ===")
print("Матрица A:")
print(A)
print(f"det(A) = {det_A} ≠ 0, обратная матрица существует")

A_inv = np.linalg.inv(A)
print("A^(-1):")
print(A_inv)

print("\n=== ПРОВЕРКА: A × A^(-1) ===")
print(A @ A_inv)
print("Должна быть единичная матрица:")
print(np.eye(2))

print("\n=== СВОЙСТВА ОБРАТНОЙ МАТРИЦЫ ===")
print("Свойство 1: (A^(-1))^(-1) = A")
print(np.linalg.inv(A_inv))

print("\nСвойство 2: det(A^(-1)) = 1 / det(A)")
print(f"det(A^(-1)) = {np.linalg.det(A_inv):.2f}")
print(f"1 / det(A) = {1/det_A:.2f}")

=== ОПРЕДЕЛИТЕЛЬ МАТРИЦЫ 2×2 ===
Матрица A:
[[1 2]
 [3 4]]
det(A) = 1×4 - 2×3 = -2.0000000000000004

=== ОПРЕДЕЛИТЕЛЬ МАТРИЦЫ 3×3 ===
Матрица B:
[[ 4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
det(B) = 42

=== ОБРАТНАЯ МАТРИЦА ===
Матрица A:
[[1 2]
 [3 4]]
det(A) = -2.0000000000000004 ≠ 0, обратная матрица существует
A^(-1):
[[-2.   1. ]
 [ 1.5 -0.5]]

=== ПРОВЕРКА: A × A^(-1) ===
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Должна быть единичная матрица:
[[1. 0.]
 [0. 1.]]

=== СВОЙСТВА ОБРАТНОЙ МАТРИЦЫ ===
Свойство 1: (A^(-1))^(-1) = A
[[1. 2.]
 [3. 4.]]

Свойство 2: det(A^(-1)) = 1 / det(A)
det(A^(-1)) = -0.50
1 / det(A) = -0.50
