In [12]:
# Упражнение 17 (Индивидуальное) - Распределение электроэнергии
import numpy as np

print("=== ЗАДАЧА: РАСПРЕДЕЛЕНИЕ ЭЛЕКТРОЭНЕРГИИ ===")
print("Условие:")
print("- Первая станция дает в 2 раза больше энергии, чем вторая")
print("- Третья станция дает на 200 МВт больше, чем вторая")
print("- Общая потребность: 1500 МВт")
print()

# 1. Составляем систему уравнений
# Обозначим:
# x - энергия первой станции
# y - энергия второй станции
# z - энергия третьей станции

# Уравнения:
# 1) x = 2y  →  x - 2y = 0
# 2) z = y + 200  →  -y + z = 200
# 3) x + y + z = 1500

print("=== СИСТЕМА УРАВНЕНИЙ ===")
print("x - 2y = 0      (первая станция дает в 2 раза больше второй)")
print("  - y + z = 200 (третья на 200 МВт больше второй)")
print("x + y + z = 1500 (общая сумма)")
print()

# 2. Матричное представление A × [x,y,z] = B
# A - матрица коэффициентов
# B - вектор правой части

A = np.array([
    [1, -2, 0],    # x - 2y = 0
    [0, -1, 1],    # -y + z = 200
    [1, 1, 1]      # x + y + z = 1500
])

B = np.array([0, 200, 1500])

print("=== МАТРИЧНОЕ ПРЕДСТАВЛЕНИЕ ===")
print("Матрица коэффициентов A:")
print(A)
print("\nВектор правой части B:")
print(B)
print()

# 3. Решаем систему
print("=== РЕШЕНИЕ СИСТЕМЫ ===")
solution = np.linalg.solve(A, B)

x = solution[0]  # первая станция
y = solution[1]  # вторая станция
z = solution[2]  # третья станция

print(f"Первая станция (x): {x:.0f} МВт")
print(f"Вторая станция (y): {y:.0f} МВт")
print(f"Третья станция (z): {z:.0f} МВт")
print()

# 4. Проверка условий
print("=== ПРОВЕРКА УСЛОВИЙ ===")
print(f"1. Первая в 2 раза больше второй? {x:.0f} = 2 × {y:.0f} ? {x == 2*y}")
print(f"   {x:.0f} = {2*y:.0f} ✓")
print()
print(f"2. Третья на 200 больше второй? {z:.0f} = {y:.0f} + 200 ? {z == y + 200}")
print(f"   {z:.0f} = {y + 200:.0f} ✓")
print()
print(f"3. Общая сумма = 1500? {x:.0f} + {y:.0f} + {z:.0f} = {x + y + z:.0f} ? {x + y + z == 1500}")
print(f"   {x + y + z:.0f} = 1500 ✓")
print()

# 5. Детальный вывод
print("=== ОТВЕТ ===")
print(f"Для обеспечения потребности города в 1500 МВт электроэнергии:")
print(f"Первая электростанция: {x:.0f} МВт")
print(f"Вторая электростанция: {y:.0f} МВт")
print(f"Третья электростанция: {z:.0f} МВт")
print()

# 6. Проверка с помощью обратной матрицы (альтернативный метод)
print("=== ПРОВЕРКА ЧЕРЕЗ ОБРАТНУЮ МАТРИЦУ ===")
A_inv = np.linalg.inv(A)
solution_alt = A_inv @ B

print("Решение через A^(-1) × B:")
print(f"Первая: {solution_alt[0]:.0f} МВт")
print(f"Вторая: {solution_alt[1]:.0f} МВт")
print(f"Третья: {solution_alt[2]:.0f} МВт")
print()

# 7. Анализ определителя
det_A = np.linalg.det(A)
print("=== АНАЛИЗ СИСТЕМЫ ===")
print(f"Определитель матрицы A: {det_A:.0f}")
print(f"det(A) ≠ 0? {abs(det_A) > 1e-10} → система имеет единственное решение")
print()

# 8. Визуализация решения (текстовая)
print("=== СХЕМА РАСПРЕДЕЛЕНИЯ ===")
total = x + y + z
print(f"Всего: {total:.0f} МВт")
print()
print(f"Первая:  {'█' * int(x/50)}{x:.0f} МВт")
print(f"Вторая:  {'█' * int(y/50)}{y:.0f} МВт")
print(f"Третья:  {'█' * int(z/50)}{z:.0f} МВт")

=== ЗАДАЧА: РАСПРЕДЕЛЕНИЕ ЭЛЕКТРОЭНЕРГИИ ===
Условие:
- Первая станция дает в 2 раза больше энергии, чем вторая
- Третья станция дает на 200 МВт больше, чем вторая
- Общая потребность: 1500 МВт

=== СИСТЕМА УРАВНЕНИЙ ===
x - 2y = 0      (первая станция дает в 2 раза больше второй)
  - y + z = 200 (третья на 200 МВт больше второй)
x + y + z = 1500 (общая сумма)

=== МАТРИЧНОЕ ПРЕДСТАВЛЕНИЕ ===
Матрица коэффициентов A:
[[ 1 -2  0]
 [ 0 -1  1]
 [ 1  1  1]]

Вектор правой части B:
[   0  200 1500]

=== РЕШЕНИЕ СИСТЕМЫ ===
Первая станция (x): 650 МВт
Вторая станция (y): 325 МВт
Третья станция (z): 525 МВт

=== ПРОВЕРКА УСЛОВИЙ ===
1. Первая в 2 раза больше второй? 650 = 2 × 325 ? True
   650 = 650 ✓

2. Третья на 200 больше второй? 525 = 325 + 200 ? True
   525 = 525 ✓

3. Общая сумма = 1500? 650 + 325 + 525 = 1500 ? True
   1500 = 1500 ✓

=== ОТВЕТ ===
Для обеспечения потребности города в 1500 МВт электроэнергии:
Первая электростанция: 650 МВт
Вторая электростанция: 325 МВт
Третья электрос